### ISSUE TITLE
Posting timeline card results in domain required error

### ISSUE THREAD

**Issue by colegleason** [SamyPesse/glass.py#2]
Using the example in the README:

```
Exception: ('Error posting card to timeline ', {u'error': {u'code': 400, u'message': u'Required', u'errors': [{u'domain': u'global', u'message': u'Required', u'reason': u'required'}]}})
```

**Comment by SamyPesse** [comment]
I never had Glasses to test this hello world (that's why I was developing an emulator).

That's a surprising error because the HelloWorld use directly the example HTTP method Google shows us at https://developers.google.com/glass/v1/reference/timeline/insert

```
## A very simple timeline item

POST /mirror/v1/timeline HTTP/1.1
Host: www.googleapis.com
Authorization: Bearer auth token
Content-Type: application/json
Content-Length: 26

{ "text": "Hello world" }
```

After reading this http://stackoverflow.com/questions/17536127/multipart-post-request-google-glass I just tested to add the content-type to application/json for post requests (985ea6868b7009d0ea3633d020aa244dceb15485). Please can you test gain with the update and tell me if it works or what you get if it's not.

**Comment by colegleason** [comment]
That seems to do it. Thanks!
